trash_collector/accounts/urls.py
from . import views

from django.urls import path


app_name = "accounts"
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
]

trash_collector/customers/urls.py
from django.urls import path, include
from . import views





# TODO: Determine what distinct pages are required for the customer user stories, add a path for each in urlpatterns

app_name = "customers"
urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.create, name='create'),
    path('one_time_day/', views.one_time_day, name='one_time_day'),
    path('change/', views.change, name='change'),
    path('account_suspend/', views.account_suspend, name='account_suspend'),
    path('account/', views.account, name='account')



        ]

trash_collector/employees/urls.py
from django.urls import path
from . import views
# TODO: Determine what distinct pages are required for the customer user stories, add a path for each in urlpatterns
app_name = "employees"
urlpatterns = [
    path('', views.index, name="index"),
    path('define_day/', views.define_day, name='define_day'),
    path('localzip_employee/', views.localzip_employee, name='localzip_employee'),
    path('customer_in_zip', views.customer_in_zip, name='customer_in_zip'),
    path('one_time_pick_up/', views.one_time_pick_up, name='one_time_pick_up'),
    path('active_accounts/', views.active_accounts, name='active_accounts'),
    path('confirm_pickup/<int:customer_id>/', views.confirm_pickup, name='confirm_pickup'),
    path('create/', views.create, name='create')
]

trash_collector/templates/base.html
{% load static %}
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html">
<head>
  <meta charset="utf-8">
  <title>{% block title %}Django Auth Tutorial{% endblock %}</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
 <link href="{% static 'main.css' %}" rel="stylesheet" type="text/css">

</head>
<body>
{% if user.is_authenticated %}
  {% for group in user.groups.all%}
    {% if group.name == "Customers" %}
    <p><nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'customers:index'%}">Main Page</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link active" aria-current="page" href="{% url 'customers:create'%}">New Customer Information</a>
        <a class="nav-link" href="{% url 'customers:change'%}">Change Pick Up Day</a>
        <a class="nav-link" href="{%url 'customers:account'%}">Account Balance</a>
        <a class="nav-link" href="{% url 'customers:account_suspend'%}">Suspend Account</a>
        <a class="nav-link" href="{% url 'customers:one_time_day'%}">One Time Pick Up</a></p>
      </div>
    </div>
  </div>
</nav></p>
    {% elif group.name == "Employees" %}
     <p><nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'employees:index'%}">Employee Navigation</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbrNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link" href="{% url 'employees:create'%}">Add New Employee Info</a>
        <a class="nav-link" href="{% url 'employees:active_accounts'%}">Active Accounts</a>
        <a class="nav-link" href="{% url 'employees:customer_in_zip'%}">Customers in local zip</a>
      </div>
    </div>
  </div>
</nav></p>
    {% endif %}
  {% endfor %}
  <p><a href="{% url 'logout' %}">Log Out</a></p>
{% endif %}
  <main>
    <h1>{% block header %} {% endblock %}</h1>
    {% block content %}
    {% endblock %}
  </main>
</script> trash
</body>
</html>
{# This is the parent view that can be inherited by any other views #}
{# Todo: Add navbar links, link to stylesheets, style layout #}

trash_collector/templates/home.html
{% extends 'base.html' %}

{% block title %}Home Portal{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  Hello {{ user.username }}. You don't have a group assigned. Please contact administrator or attempt to register again.
  <p><a href="{% url 'logout' %}">Log Out</a></p>
{% else %}
  <p>You are not logged in. Please log in or create an account.</p>
  <a href="{% url 'login' %}">Log In</a>
  <a href="{% url 'accounts:register' %}">Sign Up</a>
{% endif %}
{% endblock %}

{# This is the home page that allows a logged out user to register or log in #}