trash_collector/accounts/urls.py
from . import views

from django.urls import path


app_name = "accounts"
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
]

trash_collector/employees/urls.py
from django.urls import path
from . import views
# TODO: Determine what distinct pages are required for the customer user stories, add a path for each in urlpatterns
app_name = "employees"
urlpatterns = [
    path('', views.index, name="index"),
    path('define_day/', views.define_day, name='define_day'),
    path('localzip_employee/', views.localzip_employee, name='localzip_employee'),
    path('customer_in_zip', views.customer_in_zip, name='customer_in_zip'),
    path('one_time_pick_up/', views.one_time_pick_up, name='one_time_pick_up'),
    path('active_accounts/', views.active_accounts, name='active_accounts'),
    path('confirm_pickup/<int:customer_id>/', views.confirm_pickup, name='confirm_pickup'),
    path('create/', views.create, name='create')
]

trash_collector/employees/models.py
from django.db import models



# Create your models here.

# TODO: Create an Employee model with properties required by the user stories

class Employees(models.Model):
    name = models.CharField(max_length=50, default=None)
    zip_code = models.CharField(max_length=6, default=None)
    user = models.ForeignKey('accounts.User', default=None, on_delete=models.CASCADE)
    define_day = models.CharField(max_length=50, blank=None)

    def __str__(self):
        return self.name

trash_collector/employees/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.apps import apps
from django.urls import reverse
from .models import Employees
from datetime import date
import datetime


# Create your views here.
# TODO: Create a function for each path created in employees/urls.py. Each will need a template as well.
def index(request):
    # Get the Customer model from the other app, it can now be used to query the db
    employees = apps.get_model('employees.Employees')
    return render(request, 'employees/index.html')


def localzip_employee(request):
    user = request.user
    employee = Employees.objects.get(user_id=user.id)
    Customer: object = apps.get_model('customers.Customer')
    customers = Customer.objects.all()
    same_zipcode = []
    for customer in customers:
        if customer.zip_code == employee.zip_code and customer.service_day == employee.define_day and customer.account_active == True:
            same_zipcode.append(customer)
            context = {
                'customers': same_zipcode
            }
        elif customer.zip_code == employee.zip_code and customer.one_time_day == date.today() and customer.account_active == True:
            same_zipcode.append(customer)
            context = {
                'customers': same_zipcode
            }
    return render(request, 'employees/index.html', context)


def customer_in_zip(request):
    user = request.user
    employee = Employees.objects.get(user_id=user.id)
    Customer = apps.get_model('customers.Customer')
    customers = Customer.objects.all()
    same_zip = []
    for customer in customers:
        if customer.zip_code == employee.zip_code:
            same_zip.append(customer)
            context = {
                'customers': same_zip
            }
    return render(request, 'employees/customer_in_zip.html', context)


def one_time_pick_up(request):
    user = request.user
    employee = Employees.objects.get(user_id=user.id)
    Customer = apps.get_model('customers.Customer')
    customers = Customer.objects.all()
    same_service_day = []
    for customer in customers:
        if customer.one_time_day == date.today() and customer.zip_code == employee.zip_code:
            same_service_day.append(customer)
            context = {
                'customers': same_service_day
            }
    return render(request, 'employees/customer_in_zip.html', context)


def define_day(request):
    if request.method == 'POST':
        user = request.user
        employee = Employees.objects.get(user_id=user.id)
        employee.define_day = request.POST.get('define_day')
        employee.save()
        return HttpResponseRedirect(reverse('employees:index'))

    return render(request, 'employees/index.html')


def active_accounts(request):
    Customer = apps.get_model('customers.Customer')
    customers = Customer.objects.all()
    active_account = []
    for customer in customers:
        if customer.account_active:
            active_account.append(customer)
            context = {
                'customers': active_account
            }
    return render(request, 'employees/active_accounts.html', context)


def create(request):
    if request.method == 'POST':
        user = request.user
        name = request.POST.get('name')
        zip_code = request.POST.get('zip_code')
        new_employee = Employees(name=name, zip_code=zip_code)
        new_employee.user_id = user.id
        new_employee.save()
        return HttpResponseRedirect(reverse('employees:index'))
    else:
        return render(request, 'employees/create.html')


def showdate(request):
    datetime.datetime.now()
    return render(request, 'employees/index.html')


def confirm_pickup(request, customer_id):
    Customer = apps.get_model('customers.Customer')
    customer = Customer.objects.get(pk=customer_id)
    customer.account_balance += 25
    customer.save()
    context = {
        'customer': customer
    }
    return render(request, 'employees/confirm_pickup.html', context)

trash_collector/employees/templates/employees/active_accounts.html
<{% extends 'base.html' %}

{% block title %}{% block header %}Active Accounts {% endblock %}{% endblock %}

{% block content %}
  {% if user.is_authenticated %}
    Hello Employee {{ user.username }} This is a list of active customer accounts
{% for customer in customers %}
  <ul>
    <li><h style="fontsize: 4vw"> Name: {{customer.name}}<br>  </h>
        <h>address: {{customer.address}} <br></h>
        <h>zipcode: {{customer.zip_code}}<br></h>
        <h>pickup day: {{customer.service_day}}<br></h>
        <h>one time pick up: {{customer.one_time_day}}<br></h>
    </li>
  </ul>
{% endfor %}
  {% else %}
    <p>You are at the employee index, but you are not logged in.</p>
    <a href="{% url 'login' %}">Log In</a>
    <a href="{% url 'accounts:register' %}">Sign Up</a>
  {% endif %}
{% endblock %}

trash_collector/employees/templates/employees/confirm_pickup.html
{% extends 'base.html' %}

{% block title %}{% block header %}Active Accounts {% endblock %} {% endblock %}

{% block content %}
  {% if user.is_authenticated %}
    Hello Employee {{ user.username }}!
You have confirmed the pick up for {{customer.name}} at {{customer.address}}<br>
{{customer.name}} account balance has increased to {{customer.account_balance}}

  {% else %}
    <p>You are at the employee index, but you are not logged in.</p>
    <a href="{% url 'login' %}">Log In</a>
    <a href="{% url 'accounts:register' %}">Sign Up</a>
  {% endif %}
{% endblock %}

trash_collector/employees/templates/employees/create.html
{% extends 'base.html' %}

{% block title %}{% block header %} Employee Information {% endblock %}{% endblock %}

{% block content %}
  {% if user.is_authenticated %}
    Hello Employee {{ user.username }}!
Please enter more information so we can get to know you <br>
<form action="{% url 'employees:create' %}" method="post">
    {% csrf_token %}
    name:<input type="text" name="name" id="name"><br>
    zip_code:<input type="text" name="zip_code" id="zip_code"><br>
   <input type="submit" value ="submit">
</form>
  {% else %}
    <p>You are at the employee index, but you are not logged in.</p>
    <a href="{% url 'login' %}">Log In</a>
    <a href="{% url 'accounts:register' %}">Sign Up</a>
  {% endif %}
{% endblock %}

trash_collector/employees/templates/employees/customer_in_zip.html
<{% extends 'base.html' %}

{% block title %}{% block header %}Customers in your local zip {% endblock %}{% endblock %}

{% block content %}
  {% if user.is_authenticated %}
    Hello Employee {{ user.username }} These are the customers in your local zipcode!
{% for customer in customers %}
  <ul>
    <li><h style="fontsize: 4vw"> Name: {{customer.name}}<br>  </h>
        <h>address: {{customer.address}} <br></h>
        <h>zipcode: {{customer.zip_code}}<br></h>
        <h>pickup day: {{customer.service_day}}<br></h>
        <h>one time pick up: {{customer.one_time_day}}<br></h>
        <h>Account Active: {{customer.account_active}}<br></h>
    </li>
  </ul>
{% endfor %}
This is a list of the customer active accounts
  {% else %}
    <p>You are at the employee index, but you are not logged in.</p>
    <a href="{% url 'login' %}">Log In</a>
    <a href="{% url 'accounts:register' %}">Sign Up</a>
  {% endif %}
{% endblock %}

trash_collector/employees/templates/employees/index.html
{% extends 'base.html' %}

{% block title %}{% block header %} Employee Home {% endblock %}{% endblock %}

{% block content %}
  {% if user.is_authenticated %}
    Hello Employee {{ user.username }}!<br>
Today's Date: <input type="text" value = "{% now 'y-m-d' %}"><br>
                     <form action="{% url 'employees:define_day' %}" method="POST"><br>
    {% csrf_token %}
    Please enter the day of the week:<input type="text" name="define_day" id="define_day">
    <input type="submit" value ="submit">
    <br></form>


{% for customer in customers %}
  <ul>
    <li><h style="fontsize: 4vw"> Name: {{customer.name}}<br>  </h>
        <h>address: {{customer.address}} <br></h>
        <h>zipcode: {{customer.zip_code}}<br></h>
        <h>pickup day: {{customer.service_day}}<br></h>
        <h>one time pick up: {{customer.one_time_day}}<br></h>
        <a href=" {% url 'employees:confirm_pickup' customer.id %}"> Confirm pickup</a>
    </li>
  </ul>
{% endfor %}
<br>
<a href="{% url 'employees:localzip_employee' %}"> These are your filtered pickups! click here to see where you need to go.</a><br>


  {% endif %}
{% endblock %}

trash_collector/employees/templates/employees/localzip_employee.html
{% extends 'base.html' %}

{% block title %}{% block header %} Customers in Local Zip {% endblock %}{% endblock %}

{% block content %}
  {% if user.is_authenticated %}
    Hello Employee {{ user.username }}!
These are the customers within your local zip code!
{% for customer in selected_customers %}
{{employee.name}}
  {% else %}
    <p>You are at the employee index, but you are not logged in.</p>
    <a href="{% url 'login' %}">Log In</a>
    <a href="{% url 'accounts:register' %}">Sign Up</a>
  {% endif %}
{% endblock %}

trash_collector/employees/templates/employees/one_time_pick_up_due_out.html
{% extends 'base.html' %}

{% block title %}{% block header %}One time pick ups due out {% endblock %}{% endblock %}

{% block content %}
  {% if user.is_authenticated %}
    Hello Employee {{ user.username }}!
These are the pick ups due out
  {% else %}
    <p>You are at the employee index, but you are not logged in.</p>
    <a href="{% url 'login' %}">Log In</a>
    <a href="{% url 'accounts:register' %}">Sign Up</a>
  {% endif %}
{% endblock %}